name: Copy Changes to main-preview

on:
  push:
    branches:
      - main

jobs:
  copy-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create and Switch to main-preview Branch
        run: |
          git checkout -b main-preview
          git push --set-upstream origin main-preview

      - name: Check if main-preview branch exists
        run: |
          if git show-ref --verify --quiet refs/heads/main-preview; then
            git checkout main-preview
          else
            git checkout -b main-preview
          fi

      - name: rebase main-preview branch with main
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Copy changes from main branch"
          git push -f origin main-preview
